=== visual-topology/hyrrokkin/src/hyrrokkin/jsonschema/package/package_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "package_schema.json",
  "title": "JSONSchema description of Packages",
  "description": "Specify how Packages are defined in JSON",
  "type": "object",
  "additionalProperties": false,
  "required": ["id","metadata","node_types"],
  "properties": {
    "id": {
      "type": "string",
      "description": "Provide a unique id for this package"
    },
    "executor": {
      "type": "string"
    },
    "configuration": {
      "type": "object",
      "description": "Specify code that handles the package configuration",
      "properties": {
        "classname": {
           "description": "specify the class implementing this packages's configuration, for example (executor=python) this would look like package.subpackage.module.Class"
        }
      }
    },
    "dependencies": {
      "type": "array",
      "description": "Provide a list of the paths/urls of resource dependencies, as understood by the executor",
      "items": {
        "type": "string"
      }
    },
    "metadata": {
      "type": "object",
      "description": "Attach metadata to this package",
      "required": ["name"],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string",
          "description": "Provide a short descriptive name of this package"
        },
        "description": {
          "type": "string",
          "description": "Provide a short description (~1 paragraph) of the purpose of this package"
        },
        "version": {
          "type": "string",
          "description": "Specify the version of the package"
        }
      }
    },
    "node_types": {
      "type": "object",
      "description": "mapping from a node type id to its definition",
      "patternProperties": {
        ".*": {
          "type": "object",
          "$ref": "file:node_type_schema.json"
        }
      }
    },
    "link_types": {
      "type": "object",
      "description": "mapping from a link type id to its definition",
      "patternProperties": {
        ".*": {
          "type": "object",
          "$ref": "file:link_type_schema.json"
        }
      }
    }
  }
}

=== visual-topology/hyrrokkin/src/hyrrokkin/example_packages/numbergraph/schema.json
{
    "id": "numbergraph",
    "metadata": {
        "name": "Number Graph",
        "version": "0.0.1",
        "description": "a small example package for manipulating numbers"
    },
    "configuration": {
        "classname": "numbergraph_configuration.NumbergraphConfiguration"
    },
    "node_types": {
        "number_input_node": {
            "metadata": {
                "name": "Number Input Node",
                "description": "Define an integer value"
            },
            "output_ports": {
                "data_out": {
                    "link_type": "numbergraph:integer"
                }
            },
            "classname": "nodes.number_input_node.NumberInputNode"
        },
        "prime_factors_node": {
            "metadata": {
                "name": "Prime Factors Node",
                "description": "Calculate the prime factors of each input number"
            },
            "input_ports": {
                "data_in": {
                    "link_type": "numbergraph:integer",
                    "allow_multiple_connections": false
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "numbergraph:integerlist"
                }
            },
            "classname": "nodes.prime_factors_node.PrimeFactorsNode"
        },
        "number_display_node": {
            "metadata": {
                "name": "Number Display Node",
                "description": "Display all input numbers"
            },
            "input_ports": {
                "integer_data_in": {
                    "link_type": "numbergraph:integer"
                },
                "integerlist_data_in": {
                    "link_type": "numbergraph:integerlist"
                }
            },
            "output_ports": {
            },
            "classname": "nodes.number_display_node.NumberDisplayNode"
        }
    },
    "link_types": {
        "integer": {
            "metadata": {
                "name": "Integer",
                "description": "This type of link carries integer values"
            }
        },
        "integerlist": {
            "metadata": {
                "name": "IntegerList",
                "description": "This type of link carries values that are lists of integers"
            }
        }
    }
}

=== visual-topology/hyrrokkin/src/hyrrokkin/example_packages/numberstream/schema.json
{
    "id": "numberstream",
    "metadata": {
        "name": "Number Stream",
        "version": "0.0.1",
        "description": "a small example package for manipulating numbers"
    },
    "configuration": {
        "classname": "numberstream_configuration.NumberstreamConfiguration"
    },
    "node_types": {
        "number_input_node": {
            "metadata": {
                "name": "Number Input Node",
                "description": "Define an integer value"
            },
            "output_ports": {
                "data_out": {
                    "link_type": "numberstream:integer"
                }
            },
            "classname": "nodes.number_input_node.NumberInputNode"
        },
        "prime_factors_node": {
            "metadata": {
                "name": "Prime Factors Node",
                "description": "Calculate the prime factors of each input number"
            },
            "input_ports": {
                "data_in": {
                    "link_type": "numberstream:integer",
                    "allow_multiple_connections": false
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "numberstream:integerlist"
                }
            },
            "classname": "nodes.prime_factors_node.PrimeFactorsNode"
        },
        "number_display_node": {
            "metadata": {
                "name": "Number Display Node",
                "description": "Display all input numbers"
            },
            "input_ports": {
                "integer_data_in": {
                    "link_type": "numberstream:integer"
                },
                "integerlist_data_in": {
                    "link_type": "numberstream:integerlist"
                }
            },
            "output_ports": {
            },
            "classname": "nodes.number_display_node.NumberDisplayNode"
        }
    },
    "link_types": {
        "integer": {
            "metadata": {
                "name": "Integer",
                "description": "This type of link carries integer values"
            }
        },
        "integerlist": {
            "metadata": {
                "name": "IntegerList",
                "description": "This type of link carries values that are lists of integers"
            }
        }
    }
}

=== visual-topology/hyrrokkin/test/hyrrokkin_example_packages/numberstream/schema.json
{
    "id": "numberstream",
    "metadata": {
        "name": "Number Stream",
        "version": "0.0.1",
        "description": "package for generating and manipulating streams of numbers"
    },
    "executor": "python",
    "dependencies": [],
    "configuration": {
        "classname": "numberstream_configuration.NumberstreamConfiguration"
    },
    "node_types": {
        "number_input_node": {
            "metadata": {
                "name": "Input Number Node",
                "description": "Input a number"
            },
            "output_ports": {
                "data_out": {
                    "link_type": "numberstream:number"
                }
            },
            "classname": "nodes.number_input_node.NumberInputNode"
        },
        "sum_node": {
            "metadata": {
                "name": "Number Sum",
                "description": "Sum any input number(s) received"
            },
            "input_ports": {
                "data_in": {
                    "link_type": "numberstream:number"
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "numberstream:number"
                }
            },
            "classname": "nodes.sum_node.SumNode"
        },
         "number_display_node": {
            "metadata": {
                "name": "Number Display",
                "description": "Display any received number(s)"
            },
            "input_ports": {
                "data_in": {
                    "link_type": "numberstream:number",
                    "allow_multiple_connections": false
                }
            },
            "output_ports": {
            },
            "classname": "nodes.number_display_node.NumberDisplayNode"
        }
    },
    "link_types": {
        "number": {
            "metadata": {
                "name": "Number",
                "description": "Carry a single number"
            }
        }
    }
}
